[CI-310] Forbid deprecated API calls on master branch
Cherry-picked from reviewed and tested pull request:
https://github.com/CoreMedia/encryption.awskms-plugin/pull/61

(cherry picked from commits CoreMedia/commerce-adapter-base@a52ba08be80b362ed1489340fcfb099487b92823)
and CoreMedia/commerce-adapter-base@e4393bccd286cc75ef5cb4bb915b9bf45a9e447e)

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -63,7 +63,9 @@ jobs:
               -Dapplication.image-prefix=coremedia \
               -Dapplication.image-suffix=headless-server-commerce \
               -Dapplication.image-tag=${{ github.sha }} \
-              -Dsort.verifyFail=stop
+              -Dsort.verifyFail=stop \
+              | tee mvn-output.log
+          [[ ${PIPESTATUS} -eq 0 ]] || exit ${PIPESTATUS}
         env:
           NEXUS_GITHUB_ACTIONS_READONLY_USERNAME: ${{ secrets.NEXUS_GITHUB_ACTIONS_READONLY_USERNAME }}
           NEXUS_GITHUB_ACTIONS_READONLY_TOKEN: ${{ secrets.NEXUS_GITHUB_ACTIONS_READONLY_TOKEN }}
@@ -91,6 +93,18 @@ jobs:
       - name: Update dependency graph
         if: github.ref_name == github.event.repository.default_branch
         uses: advanced-security/maven-dependency-submission-action@v4.1.1
+
+      - name: Check for deprecated API usages
+        if: github.ref_name == github.event.repository.default_branch || github.base_ref == github.event.repository.default_branch
+        run: |
+          cat mvn-output.log | grep '^\[WARNING\]' | grep 'has been deprecated' > deprecated.log || true
+          grep -Fvf .github/workflows/config/ignored-deprecations.txt deprecated.log > violations.log || true
+          if [[ -s violations.log ]]; then
+            cat violations.log
+            echo "::error::Deprecated API calls are not allowed!"
+            exit 1
+          fi
+          echo "::notice::No deprecated API calls found"
 
       - name: Send failure notification to MS Teams
         if: ${{ !success() && github.event_name == 'schedule' }}
